feat(files): woc_elytras
BedrockTweaks/Files pull request #102
Opened 2024-06-25 05:21 UTC by Chi-a11y

<description_pr>

By checking the following boxes with an X, you ensure that:

- [X] The pack was tested ingame in at least one device.
- [ ] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [X] The pack code follows the style guide.
- [X] The commits follow the contribution guidelines.
- [X] The PR follows the contribution guidelines.

- [X] (Optional) Tested in Windows
- [X] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

2024-06-25 07:30 UTC, NSPC911 reviewed
seems fine

2024-06-25 07:31 UTC, NSPC911 requested changes
Make sure to add the description key even though it might be empty, so just add a `"description": ""` to each pack

2024-06-25 10:23 UTC, SquatchHunter commented on resource_packs/packs.json
as NSPG pointed out, make sure to include a description tag. And I believe you may need to correct how these are laid out to be in line with how the coloured slimes above (in the pack.json file) are laid out. 
That being each one with its own ID, name & description but DrAv may change how categories such as World of Colour work.

2024-06-25 14:42 UTC, Chi-a11y commented on resource_packs/packs.json
i'm not quite sure what should I put since i've checked the VT's and it didn't have any?

2024-06-25 15:04 UTC, Chi-a11y commented on resource_packs/packs.json
i've finished it, i'll wait for re-review

2024-06-25 22:08 UTC, NSPC911 commented
lgtm, need @drav0011 's review to merge anyways

2024-06-25 22:09 UTC, NSPC911 approved these changes
lgtm, need @drav0011 's review to merge anyways

2024-06-26 12:58 UTC, SquatchHunter requested changes

2024-06-26 12:59 UTC, SquatchHunter approved these changes

2024-06-26 12:59 UTC, SquatchHunter reviewed
ltgm

2024-06-26 17:46 UTC, drav0011 approved these changes
lgtm

2024-06-26 17:46 UTC, merged

2024-06-26 17:47 UTC, drav0011 commented
Next time do not forget to link the related issue or discussion that you are working on @Chi-a11y
Anyways great work