[Combinations] Bamboo Packs
BedrockTweaks/Files pull request #317
Opened 2024-09-02 14:56 UTC by SquatchHunter

this PR contains all "as is" combinations for bamboo packs, some textures still require updating and can be either updated in this PR or in a later PR

ticks a box in #71 (does not resolve, still more to do)

By checking the following boxes with an X, you ensure that:

- [ ] The pack was tested ingame in at least one device.
- [ ] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [ ] The pack code follows the style guide.
- [ ] The commits follow the contribution guidelines.
- [ ] The PR follows the contribution guidelines.

- [ ] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

2024-09-02 16:19 UTC, PAPISOP requested changes
I will review the packs later

2024-09-02 16:19 UTC, PAPISOP commented on resource_packs/packs.json
Formatting is not done and id should be the folder path such as `extras/consistent_bamboo/pack_name`

2024-09-02 16:27 UTC, SquatchHunter commented on resource_packs/packs.json
what formatting? I forgot the ids and have fixed them already.

2024-09-02 16:31 UTC, PAPISOP commented on resource_packs/packs.json
> what formatting? I forgot the ids and have fixed them already.

there is not a space between `:`, this is how it should look `"key": "value"` but urs look like this `"key":"value"`

2024-09-02 16:39 UTC, PAPISOP commented
also the pr doesnt follow contribution guidelines

2024-09-03 00:47 UTC, SquatchHunter commented on resource_packs/packs.json
already fixed.

2024-11-10 16:43 UTC, drav0011 commented
Not sure of the current state of this PR, any updates?

2024-11-11 05:04 UTC, PAPISOP commented
> Not sure of the current state of this PR, any updates?

@SquatchHunter needs to approve my pr or I could just move these combinations to my pr

2024-11-11 10:10 UTC, PAPISOP commented
> Not sure of the current state of this PR, any updates?

I have moved the bamboo combinations to my own pr (#385) while co-authoring @SquatchHunter, so @SquatchHunter you may close this pr

2024-11-11 14:04 UTC, drav0011 commented
Keeping track of this changes in #385

2024-11-11 14:04 UTC, closed without merging