feat(files): Added Trial Chamber Panorama
BedrockTweaks/Files pull request #415
Opened 2024-12-04 10:43 UTC by NSPC911

Added Trial Chamber Panorama
If you (`@drav0011`) wants, I can also add Pale Garden Panorama

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [ ] (Optional) Tested in Windows
- [x] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

2024-12-04 10:45 UTC, SquatchHunter requested changes

2024-12-04 10:45 UTC, SquatchHunter commented on resource_packs/packs.json
Vanilla Tweaks now include a "version from" in their descriptions
"description": "Replaces the default Minecraft menu panorama with a 360° view of a Trial Chamber! (from 1.21)",

2024-12-04 10:47 UTC, NSPC911 commented on resource_packs/packs.json
specify sub version like 1.21`.40` or jist 1.21?

2024-12-04 10:48 UTC, SquatchHunter commented on resource_packs/packs.json
they dont have stubs so I wouldn't - probably a personal preference / DrAv question.

2024-12-04 10:49 UTC, SquatchHunter commented
this also resolves: #416

2024-12-05 01:07 UTC, SquatchHunter approved these changes
Lgtm

2024-12-10 18:35 UTC, PAPISOP approved these changes
lgtm

2024-12-11 00:44 UTC, drav0011 commented on resource_packs/packs.json
I would add subversion for the panoramas which are from a subversion
Example 
<Update 1.21 panorama idk what it was> (1.21)
<Update 1.21.40 panorama pale oak and stuff> (1.21.40)

And talking about pale oak I would add once the next update releases no point now as is the default one
Can add a draft pr if you want and keep it there

2024-12-11 00:45 UTC, drav0011 approved these changes
lgtm

2024-12-11 00:45 UTC, merged