feat(files): Added No Pale Oak Leaves Particles
BedrockTweaks/Files pull request #418
Opened 2024-12-04 12:03 UTC by SquatchHunter

using the same method as cherry leaves, we gut the particle generator, so it no longer spawns particles.

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

2024-12-10 18:40 UTC, PAPISOP requested changes

2024-12-10 18:40 UTC, PAPISOP commented on resource_packs/files/unobtrusive/no_pale_oak_leaves_particles/particles/pale_oak_leaves_particle.json
The file should be named `pale_oak_leaves_particle.particle.json` to follow the style guide

2024-12-11 00:46 UTC, drav0011 commented on resource_packs/files/unobtrusive/no_pale_oak_leaves_particles/particles/pale_oak_leaves_particle.json
^ other wise seems good

2024-12-11 04:46 UTC, PAPISOP approved these changes
lgtm

2024-12-29 06:25 UTC, drav0011 approved these changes
lgtm

2024-12-29 06:25 UTC, merged