feat(files): All Aesthetic Packs (except More Zombies) + fix(files): formatting of packs.json
BedrockTweaks/Files pull request #89
Opened 2024-06-19 09:53 UTC by NSPC911

Packs Added:
- Accurate Scaffolding
- Fencier Fences
- Consistent Bamboo Planks
- Allay Elytra

Combinations Added:
- Accurate Scaffolding and Unobtrusive Scaffolding

Unofficial Issues Fixed:
- Added missing comma at line 1070
- Renamed all occurrences of `"pack_name"` to `"name"`

Official Issues Fixed:
- https://github.com/BedrockTweaks/Files/issues/8
- https://github.com/BedrockTweaks/Files/issues/9
- https://github.com/BedrockTweaks/Files/issues/11
- https://github.com/BedrockTweaks/Files/issues/12

By checking the following boxes with an X, you ensure that:

- [x] The pack was tested in-game in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [x] (Optional) Tested in Windows
- [x] (Optional) Tested in Android
- [ ] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

2024-06-19 09:55 UTC, NSPC911 commented
Branch name was fixed according to [CONTRIBUTING.md](https://github.com/BedrockTweaks/Files/blob/devel/CONTRIBUTING.md)

There are two things done in the PR, so the branch name had to be unnecessarily long

2024-06-20 12:55 UTC, drav0011 requested changes

2024-06-20 12:55 UTC, drav0011 commented on resource_packs/files/aesthetic/fencier_fences/textures/terrain_texture.json
When adding new files let's keep the naming as the modern minecraft naming scheme
so instead of fence_acacia, it should be acacia_fence.
Same for huge_fungus folder should not be used

Also a question are fence gates working in the pack I do not see any references to them?

2024-06-20 13:31 UTC, NSPC911 commented on resource_packs/files/aesthetic/fencier_fences/textures/terrain_texture.json
> instead of fence_acacia, it should be acacia_fence

sure

> for huge_fungus folder should not be used

so like put it in the blocks folder?

> are fence gates working in the pack

didnt know fencier fences included fence gates, because the main point of fencier fences is to make the plank lines disappear. fence gates are horizontal, so normal plank texture is good enough, unless you really want it

2024-06-20 13:41 UTC, NSPC911 commented on resource_packs/files/aesthetic/fencier_fences/textures/terrain_texture.json
![image](https://github.com/BedrockTweaks/Files/assets/87571998/5e565fc5-5859-4a58-8315-78c19f4f1df5)
ok yeah they do have the fence gates

2024-06-20 14:32 UTC, drav0011 commented on resource_packs/files/aesthetic/fencier_fences/textures/terrain_texture.json
> so like put it in the blocks folder? that contradicts your request above as it doesnt follow the modern minecraft naming scheme as fungus planks are in the huge_fungus folders

I undertand the question and the confusion, MCBE formats are a mess, as they need to make old packs still compatible with current versions. Huge fungus folder contains crimson and warped tree related blocks, but then you look for crimson in the blocks folder and there are more crimson related blocks there.
That is why I try to follow **Java's** naming scheme, where they do not need to keep backwards compatibility and if something changes all old stuff can be updated. For existing files we cannot do much about it (without complicating the packs more), but for new files it's better to follow this

> didnt know fencier fences included fence gate...

Packs should look ingame the same or as similar as possible as Vanilla Tweaks
![image](https://github.com/BedrockTweaks/Files/assets/43525295/e8480b19-9558-41e7-a44c-d7c070a9573c)

In the pull request I do not see any of those files
![image](https://github.com/BedrockTweaks/Files/assets/43525295/ed9e215b-e39b-4011-acf7-d4444108ede6)

2024-06-21 14:17 UTC, NSPC911 commented on resource_packs/files/aesthetic/fencier_fences/textures/terrain_texture.json
I added the fence gates part in https://github.com/NSPC911/BT-Files/commit/f70cbed51521db209b3c3742fe22e74e8a6216fa

2024-06-21 14:34 UTC, NSPC911 commented
Okay, so I'm not sure why it still shows this
![image](https://github.com/BedrockTweaks/Files/assets/87571998/65ee6946-d4fd-44dc-b2f8-b7585e7c767d)
even though I resolved it

2024-06-22 18:56 UTC, drav0011 commented on resource_packs/files/aesthetic/fencier_fences/textures/blocks/big_oak_fence.png
dark_oak_fence

2024-06-22 18:56 UTC, drav0011 reviewed
one small detail left

2024-06-22 19:23 UTC, drav0011 commented on resource_packs/packs.json
> +					"name": "Allay Elytra",
allay_elytra should be before vex_elytra

2024-06-22 19:27 UTC, drav0011 commented
Also 
![image](https://github.com/BedrockTweaks/Files/assets/43525295/5878abff-2d63-4571-94db-09d711883ac4)
Dark oak fence seems to not be working

2024-06-22 19:35 UTC, drav0011 commented
Fence textures do not seem to match vanilla tweaks
![image](https://github.com/BedrockTweaks/Files/assets/43525295/fb7ab171-8a74-44df-946b-f14619639716)
![image](https://github.com/BedrockTweaks/Files/assets/43525295/78d276bd-ba23-4d67-84c5-f1d2a97b756e)

2024-06-22 23:42 UTC, NSPC911 commented
mb, ill move the plank texture by a bit, and fix the dark oak fence

2024-06-23 01:07 UTC, NSPC911 commented
![Screenshot_2024-06-23-09-06-22-57_5c8300b655012b1930f2e0a7b81bf6a9.jpg](https://github.com/BedrockTweaks/Files/assets/87571998/9d74925f-33f6-4b09-bb33-e7c92e7bec23)

Okay, so the fence gates are a lot harder. This is the fence for now (haven't done the others)

2024-06-23 07:38 UTC, NSPC911 commented
![image](https://github.com/BedrockTweaks/Files/assets/87571998/aea81974-9162-4d1b-860b-d18cd1258c1a)
the fences are done (shown in blockbench, but it is accurately modelled), but the issue is with the top part, because i cant make it as smooth as the vt version

2024-06-23 09:37 UTC, NSPC911 commented
![screenshot](https://github.com/BedrockTweaks/Files/assets/87571998/bb5da35d-b6b9-427f-a60a-f95747d4aa25)

Fixed the fences, but not sure how to on the gates

![isotropic view](https://github.com/BedrockTweaks/Files/assets/87571998/e9518b1e-fa1a-447d-81e4-6b7274765f84)

2024-06-23 16:54 UTC, drav0011 requested changes
Apart from those 2 small notes, the fence gates are not looking the same
The most important difference is the smootheness of the texture, you can note in bedrock it has artifacts (random dark spots, vertical lines, large color changes)

Here are reference images in case you are not able to load a java instance


Java
![image](https://github.com/BedrockTweaks/Files/assets/43525295/6bf75ba8-df00-474c-81f4-ee407e9ad624)
![image](https://github.com/BedrockTweaks/Files/assets/43525295/ae139870-cb70-4d3f-8c2c-3b81a2fabc53)
Bedrock
![image](https://github.com/BedrockTweaks/Files/assets/43525295/c13a954a-e061-4ba9-9948-9bb3c2bd3201)
![image](https://github.com/BedrockTweaks/Files/assets/43525295/27c87883-5afd-446d-9d5e-366d3fe49f85)

2024-06-23 16:54 UTC, drav0011 commented on resource_packs/files/aesthetic/fencier_fences/fencier_fences.zip
remove file

2024-06-23 16:54 UTC, drav0011 commented on resource_packs/packs.json
>  				},
just noted about pack_description, should be description

2024-06-23 22:39 UTC, NSPC911 commented
> Apart from those 2 small notes, the fence gates are not looking the same
> The most important difference is the smootheness of the texture, you can note in bedrock it has artifacts (random dark spots, vertical lines, large color changes)

so i just remove the darkspots of the fence and what about the fence gates? whats the issue with them?

2024-06-24 02:23 UTC, NSPC911 commented
Refer to [drav.dev>general](https://discord.com/channels/567364180857061437/567364180857061439/1254611284872400987) for more info on the fence issue

2024-06-25 00:37 UTC, drav0011 approved these changes
lgtm

2024-06-25 00:37 UTC, merged