feat(files): added soyjak vault pack
BedrockTweaks/Files pull request #97
Opened 2024-06-23 08:18 UTC by yzabeast1

added the soyjak vault pack from vanilla tweaks

fixes issue #63 
By checking the following boxes with an X, you ensure that:

- [x] The pack was tested ingame in at least one device.
- [x] The pack is an existing BT pack, is a missing pack from VT or is an accepted pack/change in a discussion.
- [x] The pack code follows the style guide.
- [x] The commits follow the contribution guidelines.
- [x] The PR follows the contribution guidelines.

- [ ] (Optional) Tested in Windows
- [ ] (Optional) Tested in Android
- [x] (Optional) Tested in iOS
- [ ] (Optional) Tested in any console
- [ ] (Optional) Tested in BDS

2024-06-23 09:09 UTC, SquatchHunter commented on resource_packs/files/fun/soyjak_vault/pack.png
this should be updated and not just a blatent rip from VT

2024-06-23 10:11 UTC, NSPC911 requested changes
(so i can request changes lol)
change the pack icon because it isnt supposed to have it

2024-06-23 17:18 UTC, drav0011 requested changes
Couple of small changes, looks great the rest

2024-06-23 17:18 UTC, drav0011 commented on resource_packs/packs.json
For some reason in line 1055 on this files (after halloween_2022) there is a missing comma
Make sure to bring and merge the changes from devel to your brach

2024-06-23 17:18 UTC, drav0011 commented on resource_packs/files/fun/soyjak_vault/pack.png
great, but when scaling up the template image use closest neighbor instead of other sampling methods
This will be added to contributing guide

2024-06-23 22:51 UTC, NSPC911 commented on resource_packs/packs.json
my bad, fixed in #89 unless you merge this first

2024-06-24 16:08 UTC, drav0011 approved these changes
lgtm

2024-06-24 16:09 UTC, merged